# This task will backup the configuration
- name: Backup aruba aos configuration
  arubanetworks.aos_switch.arubaoss_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}.txt"
  register: config_output

# - name: Save configuration to backup server
#   ansible.builtin.copy:
#     src: "{{ config_output.backup_path }}"
#     dest: "/backup/cisco-cfg-backup/{{ hostvars['backup-server'].datetime }}/"
#     mode: "644"
#   when: config_output is defined
#   become: true
#   delegate_to: backup-server
# # This task removes the Current configuration... from the top of IOS routers show run
# - name: Remove non config lines - regexp
#   ansible.builtin.lineinfile:
#     path: "{{ config_output.backup_path }}"
#     line: "Building configuration..."
#     state: absent
#   delegate_to: localhost

# This task removes the Last configuration change from the top of IOS routers show run
# - name: Remove non config lines - regexp
#   ansible.builtin.lineinfile:
#     path: "{{ config_output.backup_path }}"
#     regexp: '^(Building configuration\.\.\.|! Last configuration change at .* by cisco)$'
#     state: absent
#   delegate_to: localhost
