# This task will backup the configuration
- name: Backup cisco ios configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}.txt"
  register: config_output

# # This task removes the Current configuration... from the top of IOS routers show run
# - name: Remove non config lines - regexp
#   ansible.builtin.lineinfile:
#     path: "{{ config_output.backup_path }}"
#     line: "Building configuration..."
#     state: absent
#   delegate_to: localhost

# This task removes the Last configuration change from the top of IOS routers show run
- name: Remove non config lines - regexp
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: '^(Building configuration\.\.\.|! Last configuration change at 08:45:52 UTC Thu Apr 11 2024 by cisco)$'
    state: absent
  delegate_to: localhost

- name: read cfg file content
  set_fact:
    file_content: "{{ item }}"
  with_file:
    - - "/backup/{{ hostvars['backup-server'].datetime }}/{{ inventory_hostname }}.txt"
  
- name: push cfg to gitlab
  uri:
    uri: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/commits
    headers:
      Private-Token: "{{ gitlab_access_token}}"
    validate_: no
    method: POST
    body:
      branch: master
      commit_message: create cisco cfg
      actions:
        - action: create
          file_path: "{{ inventory_hostname }}.txt"
          content: "{{ file_content }}"
    status_code: 201
    body_format: json
  delegate_to: localhost
