# This task will backup the configuration
- name: Backup cisco ios configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}.txt"
  register: config_output

# # This task removes the Current configuration... from the top of IOS routers show run
# - name: Remove non config lines - regexp
#   ansible.builtin.lineinfile:
#     path: "{{ config_output.backup_path }}"
#     line: "Building configuration..."
#     state: absent
#   delegate_to: localhost

# This task removes the Last configuration change from the top of IOS routers show run
- name: Remove non config lines - regexp
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: '^(Building configuration\.\.\.|Current configuration : 3504 bytes|! Last configuration change at 08:45:52 UTC Thu Apr 11 2024 by cisco)$'
    state: absent
  delegate_to: localhost
