## This task will backup the configuration
- name: Backup cisco nxos configuration
  cisco.nxos.nxos_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}.cfg"
  register: config_output
    
# This task removes the Last configuration change from the top of IOS routers show run
- name: Remove non config lines - regexp
  ansible.builtin.lineinfile:
    path: "{{ config_output.backup_path }}"
    regexp: '^!(Command: show running-config|Running configuration last done at:|Time:).*'
    state: absent
  delegate_to: localhost
