- name: Backup PA Configuration
  paloaltonetworks.panos.panos_export:
    provider: 
      ip_address: "192.168.10.145"
      username: "admin"
      password: "Manager1"
    category: 'configuration'
    filename: "{{ inventory_hostname }}.xml"
    file_path: "/backup/"
  # register: export_result
  delegate_to: backup-server

# - name: Save export result to a file
#   copy:
#     content: "{{ export_result.content }}"
#     dest: "/backup/{{ inventory_hostname }}.xml"