---
- name: Export configuration
  hosts: "network"
  connection: local

  vars:
    device:
      ip_address: "192.168.10.145"
      username: "admin"
      password: "Manager1"

  tasks:
    - name: Backup PA Configuration
      paloaltonetworks.panos.panos_export:
        provider: '{{ device }}'
        category: 'configuration'
        filename: '{{ inventory_hostname }}.xml'