- name: Backup PA Configuration
  paloaltonetworks.panos.panos_export:
    provider: 
      ip_address: "192.168.10.145"
      username: "admin"
      password: "Manager1"
    category: 'configuration'
    filename: "/tmp/{{ inventory_hostname }}.xml"
  register: config_output

# - name: Save export result to a file
#   copy:
#     content: "{{ config_output.content }}"
#     dest: "/backup/backup.xml"