---
- name: Export configuration
  hosts: "network"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Backup PA Configuration
      paloaltonetworks.panos.panos_export:
        provider: '{{ device }}'
        category: 'configuration'
        filename: '{{ inventory_hostname }}.xml'