---
- name: Retrieve network configurations
  hosts: network
  gather_facts: false
  
  tasks:
    - name: Create time stamp for play
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backup/
        state: directory
        mode: "755"
      become: true
      run_once: true
      delegate_to: backup-server

    - name: Backup Aruba Switch Configuration
      arubanetworks.aos_switch.arubaoss_config:
        backup: true
        backup_options:
          dir_path: /backup/cisco-cfg-backup/
          filename: "{{ inventory_hostname }}.txt"
      register: config_output
      delegate_to: backup-server
