---
- name: Fetch BIG-IP UCS
  hosts: network
  gather_facts: false
  vars:
    provider:
      server: "192.168.10.146"
      # user: "admin"
      # password: "Manager002"
      validate_certs: False

  tasks:
    - name: get current time on localhost
      command: date "+%Y-%m-%d-%H-%M"
      register: date
      delegate_to: backup-server
      run_once: True
     
    - name: set filename var
      set_fact:
        ucs: "{{ inventory_hostname + '-' + date.stdout +  '-backup.ucs' }}"

    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "{{ ucs }}"
        dest: "{{ '/f5_backup/' + ucs }}"
        provider: "{{ provider }}"
      delegate_to: backup-server
